# Generated by Django 5.2.4 on 2025-07-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='productos/default.jpg', upload_to='productos/')),
                ('Titulo', models.CharField(default='Título predeterminado', max_length=200)),
                ('Tipo', models.CharField(default='Tipo de taller predeterminado', max_length=200)),
                ('Cantidad_personas', models.CharField(default='Cantidad de personas predeterminada', max_length=200)),
                ('Duración', models.CharField(default='Duración predeterminada', max_length=200)),
                ('Descripcion', models.TextField(default='Descripción predeterminada')),
                ('Precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Diseño', models.CharField(default='libre', max_length=100)),
                ('Catering', models.BooleanField(default=False)),
            ],
        ),
    ]
