# Generated by Django 5.2.4 on 2025-07-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='productos/default.jpg', upload_to='productos/')),
                ('Titulo', models.CharField(default='Título predeterminado', max_length=200)),
                ('tipo', models.CharField(choices=[('ceramica', 'Cerámica'), ('acuarelas', 'Acuarelas'), ('cuadros', 'Cuadros')], default='ceramica', max_length=20)),
                ('Diseño', models.CharField(default='Diseño predeterminado', max_length=200)),
                ('Tamaño', models.CharField(default='Tamaño predeterminado', max_length=200)),
                ('Descripcion', models.TextField(default='Descripción predeterminada')),
                ('Precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
