# Generated by Django 5.2.4 on 2025-08-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productoimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(default='productos/default.jpg', upload_to='productos/')),
                ('Titulo', models.CharField(default='Título predeterminado', max_length=200)),
                ('tipo', models.CharField(choices=[('ceramica', 'Cerámica'), ('acuarelas', 'Acuarelas'), ('cuadros', 'Cuadros')], default='ceramica', max_length=20)),
                ('Diseño', models.CharField(default='Diseño predeterminado', max_length=200)),
                ('Tamaño', models.CharField(default='Tamaño predeterminado', max_length=200)),
                ('Descripcion', models.TextField(default='Descripción predeterminada')),
                ('Precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto'),
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
