# Generated by Django 5.2.4 on 2026-05-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_destacado_alter_producto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='coleccion',
            field=models.CharField(blank=True, choices=[('limones', 'Limones'), ('morrisyco', 'Morris&Co'), ('olivos', 'Olivos'), ('magnolias', 'Magnolias'), ('cerezos', 'Cerezos'), ('mediterraneo', 'Mediterráneo')], max_length=20, null=True, verbose_name='Colección'),
        ),
    ]
