# Generated by Django 5.2.4 on 2026-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_coleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('ceramica', 'Cerámica'), ('acuarelas', 'Acuarelas'), ('cuadros', 'Cuadros'), ('wedding', 'Wedding'), ('personalizado', 'Personalizado')], default='ceramica', max_length=20),
        ),
    ]
